#!/usr/bin/php
<?php

if(php_sapi_name() != 'cli') {
  exit();
}

use KrisRo\PhpRepublic\Console;

define('APP_ROOT', __DIR__);

if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
  define('DS', '\\');
} else {
  define('DS', '/');
}

set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__);

spl_autoload_extensions('.php');
spl_autoload_register();

define('SECTION', 'cron');

require_once 'vendor' . DS . 'autoload.php';

/**
 * Loading...
 */
$bootstrap = new \KrisRo\PhpRepublic\Bootstrap();
$bootstrap->Console();

/**
 * Processing command
 */
(new Console())->run();